queries:  
  - exclude: py/unused-local-variable
  - exclude: py/polluting-import
  - exclude: py/side-effect-in-assert
  - exclude: py/import-and-import-from
  - exclude: py/unused-import  
extraction:
  python:
    python_setup: 
      version: 3
      requirements_files: 
        - requirements.txt
      setup_py: false
