queries:  
  - exclude: py/unused-local-variable
  - exclude: py/polluting-import  
extraction:
  python:
    python_setup: 
      version: 3
      requirements_files: 
        - requirements.txt
      setup_py: false
