language: python
# ===== Linux ======
os: linux
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
jobs:
  include:
    # ======= OSX ========
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11.4
      language: shell

    - name: "Python 3.8 on macOS"
      os: osx
      osx_image: xcode11.6
      language: shell

    - name: "Python 3.9 on macOS"
      os: osx
      osx_image: xcode12.2
      language: shell

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    export PATH=$PATH:/Users/travis/Library/Python/$PYTHON/bin;
    fi 
  - python3 --version
  - python --version
  - echo $PATH
  - alias python='python3'
  - python3 -m pip install --upgrade pip
  - python3 -m pip install --upgrade ruamel.yaml pytest==5.4.3 pytest-pep8 pep8
install:
  - rm -f ~/.ssh/id_rsa
  - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - chmod og-wx ~/.ssh/authorized_keys
  - ssh-keyscan -H localhost >> ~/.ssh/known_hosts
  - python3 configure_fabsim.py  --bashrc_update=False 
  - pip freeze  
  - fab localhost install_plugin:FabDummy

script:
  - python3 -m pytest --log-cli-level=10 tests/
  - pytest --pep8  base/ deploy/ lib/ UQP/ VVP/
