#Anonymous cloning, publicly available
FabMD:
  repository: https://github.com/UCL-CCS/FabMD.git

FabFlee:
  repository: https://github.com/djgroen/FabFlee.git

FabDummy:
  repository: https://github.com/djgroen/FabDummy.git

FabUQCampaign:
  repository: https://github.com/wedeling/FabUQCampaign.git
  
FabChemShell:
  repository: https://github.com/gh3orghiu/FabChemShell.git

FabSMD:
  repository: https://github.com/potterton48/FabSMD.git

#Collaborator status required (as a precaution, as this is in development)
FabMUSCLE:
  repository: git@github.com:djgroen/FabMUSCLE.git

FabProfile:
  repository: https://github.com/NicolasMonnier/FabProfile.git

fabmogp:
  repository: https://github.com/edaub/fabmogp

FabCovid19:
  repository: https://github.com/djgroen/FabCovid19

FabCovidsim:
  repository: https://github.com/arabnejad/FabCovidsim
